// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_1_million_coin = "CgkIyIDh6tIfEAIQAQ"; // <GPGSID>
        public const string leaderboard_game_spin = "CgkIyIDh6tIfEAIQBw"; // <GPGSID>
        public const string achievement_800_level = "CgkIyIDh6tIfEAIQEw"; // <GPGSID>
        public const string achievement_100_million_coin = "CgkIyIDh6tIfEAIQBQ"; // <GPGSID>
        public const string achievement_600_level = "CgkIyIDh6tIfEAIQEQ"; // <GPGSID>
        public const string achievement_500_level = "CgkIyIDh6tIfEAIQEA"; // <GPGSID>
        public const string achievement_1000_million_coin = "CgkIyIDh6tIfEAIQCQ"; // <GPGSID>
        public const string achievement_300_level = "CgkIyIDh6tIfEAIQDg"; // <GPGSID>
        public const string achievement_400_level = "CgkIyIDh6tIfEAIQDw"; // <GPGSID>
        public const string achievement_700_level = "CgkIyIDh6tIfEAIQEg"; // <GPGSID>
        public const string achievement_10_level = "CgkIyIDh6tIfEAIQCg"; // <GPGSID>
        public const string achievement_900_level = "CgkIyIDh6tIfEAIQFA"; // <GPGSID>
        public const string achievement_over_100_ms = "CgkIyIDh6tIfEAIQGA"; // <GPGSID>
        public const string leaderboard_timed_spin = "CgkIyIDh6tIfEAIQAA"; // <GPGSID>
        public const string achievement_200_level = "CgkIyIDh6tIfEAIQDQ"; // <GPGSID>
        public const string leaderboard_timing_spin = "CgkIyIDh6tIfEAIQCA"; // <GPGSID>
        public const string achievement_over_500_ms = "CgkIyIDh6tIfEAIQHA"; // <GPGSID>
        public const string achievement_500_million_coin = "CgkIyIDh6tIfEAIQFg"; // <GPGSID>
        public const string achievement_50_level = "CgkIyIDh6tIfEAIQCw"; // <GPGSID>
        public const string achievement_over_400_ms = "CgkIyIDh6tIfEAIQGw"; // <GPGSID>
        public const string achievement_over_300_ms = "CgkIyIDh6tIfEAIQGg"; // <GPGSID>
        public const string achievement_10_million_coin = "CgkIyIDh6tIfEAIQAw"; // <GPGSID>
        public const string achievement_100_level = "CgkIyIDh6tIfEAIQDA"; // <GPGSID>
        public const string achievement_5000_million_coin = "CgkIyIDh6tIfEAIQFw"; // <GPGSID>
        public const string achievement_999_level = "CgkIyIDh6tIfEAIQFQ"; // <GPGSID>
        public const string achievement_over_200_ms = "CgkIyIDh6tIfEAIQGQ"; // <GPGSID>
        public const string achievement_over_600_ms = "CgkIyIDh6tIfEAIQHQ"; // <GPGSID>

}

