// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_900__ = "CgkIyIDh6tIfEAIQFA"; // <GPGSID>
        public const string achievement_400_ms_ = "CgkIyIDh6tIfEAIQGw"; // <GPGSID>
        public const string leaderboard_timing_spin_ = "CgkIyIDh6tIfEAIQCA"; // <GPGSID>
        public const string achievement_1000__ = "CgkIyIDh6tIfEAIQCQ"; // <GPGSID>
        public const string achievement_600_ms_ = "CgkIyIDh6tIfEAIQHQ"; // <GPGSID>
        public const string achievement_999__ = "CgkIyIDh6tIfEAIQFQ"; // <GPGSID>
        public const string achievement_50_ = "CgkIyIDh6tIfEAIQCw"; // <GPGSID>
        public const string leaderboard_timed_spin_ = "CgkIyIDh6tIfEAIQAA"; // <GPGSID>
        public const string achievement_500_ms_ = "CgkIyIDh6tIfEAIQHA"; // <GPGSID>
        public const string achievement_300_ms_ = "CgkIyIDh6tIfEAIQGg"; // <GPGSID>
        public const string achievement_200_ms_ = "CgkIyIDh6tIfEAIQGQ"; // <GPGSID>
        public const string achievement_100_ms_ = "CgkIyIDh6tIfEAIQGA"; // <GPGSID>
        public const string achievement_5000__ = "CgkIyIDh6tIfEAIQFw"; // <GPGSID>
        public const string leaderboard_game_spin_ = "CgkIyIDh6tIfEAIQBw"; // <GPGSID>
        public const string achievement_10__ = "CgkIyIDh6tIfEAIQCg"; // <GPGSID>
        public const string achievement_1__ = "CgkIyIDh6tIfEAIQAQ"; // <GPGSID>
        public const string achievement_100__ = "CgkIyIDh6tIfEAIQDA"; // <GPGSID>
        public const string achievement_200__ = "CgkIyIDh6tIfEAIQDQ"; // <GPGSID>
        public const string achievement_300__ = "CgkIyIDh6tIfEAIQDg"; // <GPGSID>
        public const string achievement_400__ = "CgkIyIDh6tIfEAIQDw"; // <GPGSID>
        public const string achievement_500__ = "CgkIyIDh6tIfEAIQFg"; // <GPGSID>
        public const string achievement_600__ = "CgkIyIDh6tIfEAIQEQ"; // <GPGSID>
        public const string achievement_700__ = "CgkIyIDh6tIfEAIQEg"; // <GPGSID>
        public const string achievement_800__ = "CgkIyIDh6tIfEAIQEw"; // <GPGSID>

}

